### ISSUE TITLE
Implement `inspect()` to select nodes in the inspector.

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/devtools-highlighter#1]
It would be great if each element displayed in the list would have a button next to them that took you to the inspector panel, with the right element being selected.
This is, in theory, possible by using the `inspect` web-extension API, but it looks like it can only be used while using the [eval API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/devtools.inspectedWindow/eval)

**Comment by rajatvijay** [comment]
Any pointers on where should I start working on this?

**Comment by captainbrosset** [comment]
The API for doing this is a little odd:
you can call a function named `inspect()` and this function takes a DOM node as argument. If the supplied DOM node actually exists in the page, it will select it in the inspector. That's all good, that's what we need here. But `inspect()` call only be used from an eval expression like this: `browser.devtools.inspectedWindow.eval(expression)`

For example: 
`browser.devtools.inspectedWindow.eval('inspect(someDomNode)');`

My understanding is that we would call eval from the panel (`src/devtools/panel/devtools-panel.js`) when a button in the UI is clicked. But then we would have to find a way to identify the DOM node that needs to be inspected. 
I don't know if the eval expression gets executed in the same scope as the one the content script runs in (`src/content_scripts/content.js`).
If it does, then that would be easy, because there's a variable in that scope called `currentlyHighlighted` that contains the references to all currently highlighted DOM nodes. So if the second button was clicked for instance, we would do this:

`browser.devtools.inspectedWindow.eval('inspect(currentlyHighlighted[1])');`

But I don't know if we can do that.
If we can't, we'd have to find another way to identify the element, maybe through a CSS selector (if the element has an ID, use that, if it has a unique class, use that, etc.)

Does that make sense? Do you want to start looking into this?

**Comment by rajatvijay** [comment]
Yeah, I am starting to look into this.

**Comment by rajatvijay** [comment]
Hey, one question just out of curiosity: 

Is there a specific reason for using **one-time connection** while sending messages from the background script to the dev tools panels script and also the other way around i.e.

`browser.runtime.sendMessage` and `browser.runtime.onMessage`.

On the other hand, we are using **long-lived connection** using port when communicating between content script and the background script i.e.

`port.postMessage` and `port.onMessage`

### ?

**Comment by captainbrosset** [comment]
No particular reason so far. If it helps, we could use long-lived connections everywhere.

**Comment by captainbrosset** [comment]
Closing this, merged!
