### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by PeterDavidCarter** [captainbrosset/devtools-highlighter#16]
You still looking for help with the repo? If so, do you have a chat channel? Usually it's easier to help if you can find out what the other person wants to achieve and can ask questions about the way they structured their code etc.

(response to https://twitter.com/patrickbrosset/status/938904668419354624)

**Comment by captainbrosset** [comment]
Good point. I have updated the README with a new section to get in touch on [Slack](https://github.com/captainbrosset/devtools-highlighter#getting-in-touch).
