### ISSUE TITLE
File not found in FF 59b01

### ISSUE THREAD

**Issue by richardkmichael** [captainbrosset/devtools-highlighter#20]
The addon installed without problem in FF 59b01.  However, when I view a page, open the devtools and select the new highlighter tab, this `file not found` error occurs immediately.

`Firefox can’t find the file at moz-extension://78f167dc-2fc4-a146-9633-d608462881ba/devtools/devtools/panel/panel.html.`

I enabled addon debugging in `about:debugging`, and I found this additional information (there was more logged, but I don't believe it was related to this addon).

`NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIWebNavigation.loadURIWithOptions]  browser.xml:150`

**Comment by captainbrosset** [comment]
Thanks for logging this, and so sorry I didn't see the issue before now. I guess I must have just missed it somehow.
I know where this comes from, and it's a mystery how I didn't detect that before releasing. I'll make a new release now.

**Comment by richardkmichael** [comment]
I've updated and it works fine, thank you for the very fast reply.  This is a very useful extension, I think the functionality could even go into the core Inspector.  Thanks!
