### ISSUE TITLE
The "Select" link does not appear on Chrome

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/devtools-highlighter#26]
Here's how it should look like (currently in Firefox):
<img width="859" alt="select-link" src="https://user-images.githubusercontent.com/1152698/36584543-6b215b14-187a-11e8-9e82-08960a4f5dcf.PNG">

In Chrome however, the "select" links are just not shown at all.
I have not investigated this yet, so I don't know where it is coming from.

**Comment by jonathanGB** [comment]
Just tried on Chrome (v64) and I see the *select* links.

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/8869660/36608253-4ae78a68-1897-11e8-859e-dfb235617b79.png">

**Comment by captainbrosset** [comment]
Hm, you know what, maybe I got confused and mixed the 2 links up. The scroll to links are missing. But maybe it's just because elements appear as hidden on chrome because of issue #24 .
So maybe they're just duplicate issues.
