### ISSUE TITLE
"Type" select does not open on Windows 7

### ISSUE THREAD

**Issue by juliandescottes** [captainbrosset/devtools-highlighter#30]
Was just trying the extension on my windows 7 machine, and I noticed that the select input could not be opened (tried on FF58 and FF60, with the latest version of the extension). Tried with a clean profile as well. 

There's no error anywhere, not sure what's going on. Doubt it is specific to this addon though.

**Comment by juliandescottes** [comment]
Definitely not specific to this extension, created https://bugzilla.mozilla.org/show_bug.cgi?id=1440902 to track this.

**Comment by captainbrosset** [comment]
Yeah, I've seen this too. I think this is https://bugzilla.mozilla.org/show_bug.cgi?id=1422960

**Comment by captainbrosset** [comment]
Actually, this one was closed as a dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1417043

**Comment by juliandescottes** [comment]
Yes I duped mine as well, a bit sad :(
