### ISSUE TITLE
Auto-remove all highlighters on close/reload.

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/devtools-highlighter#7]
Auto-remove all highlighters on close/reload.

**Comment by rajatvijay** [comment]
This doesn't apply now since:

1. We are highlighting the node only when the user hovers on it from the panel
2. We are using a highlighter layer instead.

@captainbrosset, right?

**Comment by captainbrosset** [comment]
Correct. Thanks for noticing. Closing now.
